name: "flake.lock: update inputs"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 1'

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 1
          ref: master
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v19
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v27
        with:
          git-author-name: "nukdokplex"
          git-author-email: "nukdokplex@nukdokplex.ru"
          git-committer-name: "nukdokplex"
          git-committer-email: "nukdokplex@nukdokplex.ru"
          branch: flake-update
          pr-title: "flake.lock: Update"
          pr-assignees: nukdokplex
          sign-commits: true
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-fingerprint: ${{ secrets.GPG_FINGERPRINT }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
