name: nix-check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 1
          lfs: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20
      - name: Run flake checks
        run: nix --print-build-logs flake check --all-systems --accept-flake-config
